apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadup-gitops-app
  labels:
    app: loadup-gitops-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: loadup-gitops-app
  template:
    metadata:
      labels:
        app: loadup-gitops-app
    spec:
      containers:
      - name: app
        image: petrpliska/loadup-gitops-app:1.0.0
        ports:
        - containerPort: 80